apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: green
  name: green
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: green
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: green-vol
          mountPath: /usr/share/nginx/html
        env:
          - name: PORT_NUM 
            valueFrom: 
              configMapKeyRef: 
                name: green-cm-1
                key: http-port 
      volumes:
      - name: green-vol
        configMap:
          name: green-cm
