apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: basicpod
  name: basicpod1
spec:
  containers:
  - image: nginx
    name: basicpod1
    ports:
    - containerPort: 80
    resources: {}
  - image: fluent/fluentd
    name: fdlogger
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
