openapi: 3.0.0
info:
  title: SmartBear HR API
  description: An API that allows users to obtain existing information of employees
    or post info of new employees
  termsOfService: https://smartbear.com/terms-of-service
  contact:
    name: Tanveer
    url: smartbear.com
    email: tanveer@smartbear.com
  license:
    name: SmartBear License
    url: https://license.foo.com
  version: 2.0.0
servers:
- url: https://virtserver.swaggerhub.com/tanalam2411/HR_API_OAS3.0/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://dev.foo.com/v1
  description: Dev Server
- url: https://prod.foo.com/v1
  description: Prod Server
paths:
  /employees:
    get:
      description: Obtain information about employees from the HT database
      parameters:
      - name: bodyLimit
        in: query
        description: The amount of employees returned
        required: false
        style: form
        explode: true
        schema:
          maximum: 20
          minimum: 10
          type: integer
          example: 15
      - name: pageLimit
        in: query
        description: The pages to return employees info
        required: false
        style: form
        explode: true
        schema:
          maximum: 5
          minimum: 1
          type: integer
          example: 2
      responses:
        200:
          description: Successful pull of employee info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
    post:
      description: Creates a new employee in the database
      requestBody:
        content:
          applicaton/json:
            schema:
              $ref: '#/components/schemas/Employee'
          application/xml:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        200:
          description: Successfully created a new employee
  /employee/{id}:
    get:
      description: Obtain information about specific employee
      parameters:
      - name: id
        in: path
        description: The ID of the employee
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 54
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
            application/xml:
              schema:
                $ref: '#/components/schemas/Employee'
components:
  schemas:
    Employees:
      type: array
      description: Array of employee info
      items:
        $ref: '#/components/schemas/Employee'
    Employee:
      type: object
      properties:
        id:
          type: integer
          example: 4
        employee name:
          type: string
          example: Tanveer Alam
        employee title:
          type: string
          example: Market Manager
      description: Model containing employee info
