apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-test
spec:
  steps:
    - name: mvn-test
      image: on2411/testcontainers:latest
      command:
        - /opt/apache-maven-3.8.1/bin/mvn
      args: ['test', '-Dspring-boot.run.profiles=test']
      volumeMounts:
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
