---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-problem-detector-config
  namespace: kube-system
data:
  net-cgroup-system-stats-monitor.json: '{"net": {"metricsConfigs": {"net/rx_bytes":
    {"displayName": "net/rx_bytes"}, "net/rx_packets": {"displayName": "net/rx_packets"},
    "net/rx_errors": {"displayName": "net/rx_errors"}, "net/rx_dropped": {"displayName":
    "net/rx_dropped"}, "net/rx_fifo": {"displayName": "net/rx_fifo"}, "net/rx_frame":
    {"displayName": "net/rx_frame"}, "net/rx_compressed": {"displayName": "net/rx_compressed"},
    "net/rx_multicast": {"displayName": "net/rx_multicast"}, "net/tx_bytes": {"displayName":
    "net/tx_bytes"}, "net/tx_packets": {"displayName": "net/tx_packets"}, "net/tx_errors":
    {"displayName": "net/tx_errors"}, "net/tx_dropped": {"displayName": "net/tx_dropped"},
    "net/tx_fifo": {"displayName": "net/tx_fifo"}, "net/tx_collisions": {"displayName":
    "net/tx_collisions"}, "net/tx_carrier": {"displayName": "net/tx_carrier"}, "net/tx_compressed":
    {"displayName": "net/tx_compressed"}}}, "invokeInterval": "120s"}'
  docker-monitor-filelog.json: '{"plugin": "filelog", "pluginConfig": {"timestamp":
    "^time=\"(\\S*)\"", "message": "msg=\"([^\n]*)\"", "timestampFormat": "2006-01-02T15:04:05.999999999-07:00"},
    "logPath": "/var/log/docker.log", "lookback": "5m", "bufferSize": 10, "source":
    "docker-monitor", "conditions": [], "rules": [{"type": "temporary", "reason":
    "CorruptDockerImage", "pattern": "Error trying v2 registry: failed to register
    layer: rename /var/lib/docker/image/(.+) /var/lib/docker/image/(.+): directory
    not empty.*"}]}'
  systemd-monitor.json: '{"plugin": "journald", "pluginConfig": {"source": "systemd"},
    "logPath": "/var/log/journal", "lookback": "5m", "bufferSize": 10, "source": "systemd-monitor",
    "metricsReporting": true, "conditions": [], "rules": [{"type": "temporary", "reason":
    "KubeletStart", "pattern": "Started Kubernetes kubelet."}, {"type": "temporary",
    "reason": "DockerStart", "pattern": "Starting Docker Application Container Engine..."},
    {"type": "temporary", "reason": "ContainerdStart", "pattern": "Starting containerd
    container runtime..."}]}'
  network-problem-monitor.json: '{"plugin": "custom", "pluginConfig": {"invoke_interval":
    "30s", "timeout": "5s", "max_output_length": 80, "concurrency": 3}, "source":
    "network-custom-plugin-monitor", "metricsReporting": true, "conditions": [], "rules":
    [{"type": "temporary", "reason": "ConntrackFull", "path": "./config/plugin/network_problem.sh",
    "timeout": "3s"}]}'
  system-stats-monitor.json: '{"cpu": {"metricsConfigs": {"cpu/load_15m": {"displayName":
    "cpu/load_15m"}, "cpu/load_1m": {"displayName": "cpu/load_1m"}, "cpu/load_5m":
    {"displayName": "cpu/load_5m"}, "cpu/runnable_task_count": {"displayName": "cpu/runnable_task_count"},
    "cpu/usage_time": {"displayName": "cpu/usage_time"}, "system/cpu_stat": {"displayName":
    "system/cpu_stat"}, "system/interrupts_total": {"displayName": "system/interrupts_total"},
    "system/processes_total": {"displayName": "system/processes_total"}, "system/procs_blocked":
    {"displayName": "system/procs_blocked"}, "system/procs_running": {"displayName":
    "system/procs_running"}}}, "disk": {"includeAllAttachedBlk": true, "includeRootBlk":
    true, "lsblkTimeout": "5s", "metricsConfigs": {"disk/avg_queue_len": {"displayName":
    "disk/avg_queue_len"}, "disk/bytes_used": {"displayName": "disk/bytes_used"},
    "disk/io_time": {"displayName": "disk/io_time"}, "disk/merged_operation_count":
    {"displayName": "disk/merged_operation_count"}, "disk/operation_bytes_count":
    {"displayName": "disk/operation_bytes_count"}, "disk/operation_count": {"displayName":
    "disk/operation_count"}, "disk/operation_time": {"displayName": "disk/operation_time"},
    "disk/weighted_io": {"displayName": "disk/weighted_io"}}}, "host": {"metricsConfigs":
    {"host/uptime": {"displayName": "host/uptime"}}}, "invokeInterval": "60s", "memory":
    {"metricsConfigs": {"memory/anonymous_used": {"displayName": "memory/anonymous_used"},
    "memory/bytes_used": {"displayName": "memory/bytes_used"}, "memory/dirty_used":
    {"displayName": "memory/dirty_used"}, "memory/page_cache_used": {"displayName":
    "memory/page_cache_used"}, "memory/unevictable_used": {"displayName": "memory/unevictable_used"}}},
    "osFeature": {"KnownModulesConfigPath": "config/guestosconfig/known-modules.json",
    "metricsConfigs": {"system/os_feature": {"displayName": "system/os_feature"}}}}'
  abrt-adaptor.json: '{"plugin": "journald", "pluginConfig": {"source": "abrt-notification"},
    "logPath": "/var/log/journal", "lookback": "5m", "bufferSize": 10, "source": "abrt-adaptor",
    "conditions": [], "rules": [{"type": "temporary", "reason": "CCPPCrash", "pattern":
    "Process \\d+ \\(\\S+\\) crashed in .*"}, {"type": "temporary", "reason": "UncaughtException",
    "pattern": "Process \\d+ \\(\\S+\\) of user \\d+ encountered an uncaught \\S+
    exception"}, {"type": "temporary", "reason": "XorgCrash", "pattern": "Display
    server \\S+ crash in \\S+"}, {"type": "temporary", "reason": "VMcore", "pattern":
    "System encountered a fatal error in \\S+"}, {"type": "temporary", "reason": "Kerneloops",
    "pattern": "System encountered a non-fatal error in \\S+"}]}'
  windows-containerd-monitor-filelog.json: '{"plugin": "filelog", "pluginConfig":
    {"timestamp": "^time=\"(\\S*)\"", "message": "msg=\"([^\n]*)\"", "timestampFormat":
    "2006-01-02T15:04:05.999999999-07:00"}, "logPath": "C:\\Program Files\\containerd\\containerd.log",
    "lookback": "5m", "bufferSize": 10, "source": "docker-monitor", "conditions":
    [], "rules": [{"type": "temporary", "reason": "BadCNIConfig", "pattern": "failed
    to reload cni configuration.*"}]}'
  health-checker-containerd.json: '{"plugin": "custom", "pluginConfig": {"invoke_interval":
    "10s", "timeout": "3m", "max_output_length": 80, "concurrency": 1}, "source":
    "health-checker", "metricsReporting": true, "conditions": [{"type": "ContainerRuntimeUnhealthy",
    "reason": "ContainerRuntimeIsHealthy", "message": "Container runtime on the node
    is functioning properly"}], "rules": [{"type": "permanent", "condition": "ContainerRuntimeUnhealthy",
    "reason": "ContainerdUnhealthy", "path": "/home/kubernetes/bin/health-checker",
    "args": ["--component=cri", "--enable-repair=true", "--cooldown-time=2m", "--health-check-timeout=60s"],
    "timeout": "3m"}]}'
  health-checker-docker.json: '{"plugin": "custom", "pluginConfig": {"invoke_interval":
    "10s", "timeout": "3m", "max_output_length": 80, "concurrency": 1}, "source":
    "health-checker", "metricsReporting": true, "conditions": [{"type": "ContainerRuntimeUnhealthy",
    "reason": "ContainerRuntimeIsHealthy", "message": "Container runtime on the node
    is functioning properly"}], "rules": [{"type": "permanent", "condition": "ContainerRuntimeUnhealthy",
    "reason": "DockerUnhealthy", "path": "/home/kubernetes/bin/health-checker", "args":
    ["--component=docker", "--enable-repair=true", "--cooldown-time=2m", "--health-check-timeout=60s"],
    "timeout": "3m"}]}'
  health-checker-kubelet.json: '{"plugin": "custom", "pluginConfig": {"invoke_interval":
    "10s", "timeout": "3m", "max_output_length": 80, "concurrency": 1}, "source":
    "health-checker", "metricsReporting": true, "conditions": [{"type": "KubeletUnhealthy",
    "reason": "KubeletIsHealthy", "message": "kubelet on the node is functioning properly"}],
    "rules": [{"type": "permanent", "condition": "KubeletUnhealthy", "reason": "KubeletUnhealthy",
    "path": "/home/kubernetes/bin/health-checker", "args": ["--component=kubelet",
    "--enable-repair=true", "--cooldown-time=1m", "--health-check-timeout=10s"], "timeout":
    "3m"}]}'
  kernel-monitor-counter.json: '{"plugin": "custom", "pluginConfig": {"invoke_interval":
    "5m", "timeout": "1m", "max_output_length": 80, "concurrency": 1}, "source": "kernel-monitor",
    "metricsReporting": true, "conditions": [{"type": "FrequentUnregisterNetDevice",
    "reason": "NoFrequentUnregisterNetDevice", "message": "node is functioning properly"}],
    "rules": [{"type": "permanent", "condition": "FrequentUnregisterNetDevice", "reason":
    "UnregisterNetDevice", "path": "/home/kubernetes/bin/log-counter", "args": ["--journald-source=kernel",
    "--log-path=/var/log/journal", "--lookback=20m", "--count=3", "--pattern=unregister_netdevice:
    waiting for \\w+ to become free. Usage count = \\d+"], "timeout": "1m"}]}'
  kernel-monitor-filelog.json: '{"plugin": "filelog", "pluginConfig": {"timestamp":
    "^.{15}", "message": "kernel: \\[.*\\] (.*)", "timestampFormat": "Jan _2 15:04:05"},
    "logPath": "/var/log/kern.log", "lookback": "5m", "bufferSize": 10, "source":
    "kernel-monitor", "conditions": [{"type": "KernelDeadlock", "reason": "KernelHasNoDeadlock",
    "message": "kernel has no deadlock"}], "rules": [{"type": "temporary", "reason":
    "OOMKilling", "pattern": "Killed process \\d+ (.+) total-vm:\\d+kB, anon-rss:\\d+kB,
    file-rss:\\d+kB.*"}, {"type": "temporary", "reason": "TaskHung", "pattern": "task
    \\S+:\\w+ blocked for more than \\w+ seconds\\."}, {"type": "temporary", "reason":
    "UnregisterNetDevice", "pattern": "unregister_netdevice: waiting for \\w+ to become
    free. Usage count = \\d+"}, {"type": "temporary", "reason": "KernelOops", "pattern":
    "BUG: unable to handle kernel NULL pointer dereference at .*"}, {"type": "temporary",
    "reason": "KernelOops", "pattern": "divide error: 0000 \\[#\\d+\\] SMP"}, {"type":
    "permanent", "condition": "KernelDeadlock", "reason": "AUFSUmountHung", "pattern":
    "task umount\\.aufs:\\w+ blocked for more than \\w+ seconds\\."}, {"type": "permanent",
    "condition": "KernelDeadlock", "reason": "DockerHung", "pattern": "task docker:\\w+
    blocked for more than \\w+ seconds\\."}]}'
  custom-plugin-monitor.json: '{"plugin": "custom", "pluginConfig": {"invoke_interval":
    "30s", "timeout": "5s", "max_output_length": 80, "concurrency": 3, "enable_message_change_based_condition_update":
    false}, "source": "ntp-custom-plugin-monitor", "metricsReporting": true, "conditions":
    [{"type": "NTPProblem", "reason": "NTPIsUp", "message": "ntp service is up"}],
    "rules": [{"type": "temporary", "reason": "NTPIsDown", "path": "./config/plugin/check_ntp.sh",
    "timeout": "3s"}, {"type": "permanent", "condition": "NTPProblem", "reason": "NTPIsDown",
    "path": "./config/plugin/check_ntp.sh", "timeout": "3s"}]}'
  systemd-monitor-counter.json: '{"plugin": "custom", "pluginConfig": {"invoke_interval":
    "5m", "timeout": "1m", "max_output_length": 80, "concurrency": 1}, "source": "systemd-monitor",
    "metricsReporting": true, "conditions": [{"type": "FrequentKubeletRestart", "reason":
    "NoFrequentKubeletRestart", "message": "kubelet is functioning properly"}, {"type":
    "FrequentDockerRestart", "reason": "NoFrequentDockerRestart", "message": "docker
    is functioning properly"}, {"type": "FrequentContainerdRestart", "reason": "NoFrequentContainerdRestart",
    "message": "containerd is functioning properly"}], "rules": [{"type": "permanent",
    "condition": "FrequentKubeletRestart", "reason": "FrequentKubeletRestart", "path":
    "/home/kubernetes/bin/log-counter", "args": ["--journald-source=systemd", "--log-path=/var/log/journal",
    "--lookback=20m", "--delay=5m", "--count=5", "--pattern=Started Kubernetes kubelet."],
    "timeout": "1m"}, {"type": "permanent", "condition": "FrequentDockerRestart",
    "reason": "FrequentDockerRestart", "path": "/home/kubernetes/bin/log-counter",
    "args": ["--journald-source=systemd", "--log-path=/var/log/journal", "--lookback=20m",
    "--count=5", "--pattern=Starting Docker Application Container Engine..."], "timeout":
    "1m"}, {"type": "permanent", "condition": "FrequentContainerdRestart", "reason":
    "FrequentContainerdRestart", "path": "/home/kubernetes/bin/log-counter", "args":
    ["--journald-source=systemd", "--log-path=/var/log/journal", "--lookback=20m",
    "--count=5", "--pattern=Starting containerd container runtime..."], "timeout":
    "1m"}]}'
  docker-monitor-counter.json: '{"plugin": "custom", "pluginConfig": {"invoke_interval":
    "5m", "timeout": "1m", "max_output_length": 80, "concurrency": 1}, "source": "docker-monitor",
    "conditions": [{"type": "CorruptDockerOverlay2", "reason": "NoCorruptDockerOverlay2",
    "message": "docker overlay2 is functioning properly"}], "rules": [{"type": "permanent",
    "condition": "CorruptDockerOverlay2", "reason": "CorruptDockerOverlay2", "path":
    "/home/kubernetes/bin/log-counter", "args": ["--journald-source=dockerd", "--log-path=/var/log/journal",
    "--lookback=5m", "--count=10", "--pattern=returned error: readlink /var/lib/docker/overlay2.*:
    invalid argument.*"], "timeout": "1m"}]}'
  kernel-monitor.json: '{"plugin": "kmsg", "logPath": "/dev/kmsg", "lookback": "5m",
    "bufferSize": 10, "source": "kernel-monitor", "metricsReporting": true, "conditions":
    [{"type": "KernelDeadlock", "reason": "KernelHasNoDeadlock", "message": "kernel
    has no deadlock"}, {"type": "ReadonlyFilesystem", "reason": "FilesystemIsNotReadOnly",
    "message": "Filesystem is not read-only"}], "rules": [{"type": "temporary", "reason":
    "OOMKilling", "pattern": "Killed process \\d+ (.+) total-vm:\\d+kB, anon-rss:\\d+kB,
    file-rss:\\d+kB.*"}, {"type": "temporary", "reason": "TaskHung", "pattern": "task
    [\\S ]+:\\w+ blocked for more than \\w+ seconds\\."}, {"type": "temporary", "reason":
    "UnregisterNetDevice", "pattern": "unregister_netdevice: waiting for \\w+ to become
    free. Usage count = \\d+"}, {"type": "temporary", "reason": "KernelOops", "pattern":
    "BUG: unable to handle kernel NULL pointer dereference at .*"}, {"type": "temporary",
    "reason": "KernelOops", "pattern": "divide error: 0000 \\[#\\d+\\] SMP"}, {"type":
    "temporary", "reason": "Ext4Error", "pattern": "EXT4-fs error .*"}, {"type": "temporary",
    "reason": "Ext4Warning", "pattern": "EXT4-fs warning .*"}, {"type": "temporary",
    "reason": "IOError", "pattern": "Buffer I/O error .*"}, {"type": "temporary",
    "reason": "MemoryReadError", "pattern": "CE memory read error .*"}, {"type": "permanent",
    "condition": "KernelDeadlock", "reason": "AUFSUmountHung", "pattern": "task umount\\.aufs:\\w+
    blocked for more than \\w+ seconds\\."}, {"type": "permanent", "condition": "KernelDeadlock",
    "reason": "DockerHung", "pattern": "task docker:\\w+ blocked for more than \\w+
    seconds\\."}, {"type": "permanent", "condition": "ReadonlyFilesystem", "reason":
    "FilesystemIsReadOnly", "pattern": "Remounting filesystem read-only"}]}'
  docker-monitor.json: '{"plugin": "journald", "pluginConfig": {"source": "dockerd"},
    "logPath": "/var/log/journal", "lookback": "5m", "bufferSize": 10, "source": "docker-monitor",
    "metricsReporting": true, "conditions": [{"type": "CorruptDockerOverlay2", "reason":
    "NoCorruptDockerOverlay2", "message": "docker overlay2 is functioning properly"}],
    "rules": [{"type": "temporary", "reason": "CorruptDockerImage", "pattern": "Error
    trying v2 registry: failed to register layer: rename /var/lib/docker/image/(.+)
    /var/lib/docker/image/(.+): directory not empty.*"}, {"type": "permanent", "condition":
    "CorruptDockerOverlay2", "reason": "CorruptDockerOverlay2", "pattern": "returned
    error: readlink /var/lib/docker/overlay2.*: invalid argument.*"}, {"type": "temporary",
    "reason": "DockerContainerStartupFailure", "pattern": "OCI runtime start failed:
    container process is already dead: unknown"}]}'

