apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: monitoring
spec:
  selector:
    app: node-exporter
  type: NodePort
  ports:
    - port: 9100
      targetPort: 9100
