apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-app2
  name: my-app2
spec:
  containers:
  - image: nginx
    name: my-app2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
